login: &login
  adapter: postgresql
  username: procore_db
  password: <%= ENV['POSTGRES_DB_PASSWORD'] %>
#  host: localhost
  host: db

# For local server
development:
  <<: *login
  database: procore_development

production:
  <<: *login
  database: procore_development

staging:
  <<: *login
  database: procore_full
  host: 192.168.33.251

test:
  <<: *login
  database: procore_test
